package com.wows.base;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BaseDao<T, E> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_platform
     *
     * @mbg.generated
     */
    int countByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_platform
     *
     * @mbg.generated
     */
    int deleteByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_platform
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_platform
     *
     * @mbg.generated
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_platform
     *
     * @mbg.generated
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_platform
     *
     * @mbg.generated
     */
    List<T> selectByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_platform
     *
     * @mbg.generated
     */
    T selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_platform
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_platform
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(T record);
}